### ISSUE TITLE
Web Development: Contact Page

### ISSUE THREAD

**Issue by KL1217** [hicodingclub/askmschen-front#16]
This task is to program the School Application and Transfer part of the Service Page.

Click the link below to follow the layout.
https://www.figma.com/file/Y8crYpHpCci66i5ylS44YK/Contact-Page?node-id=1%3A2

Deadline 8/28/20

Please assign yourself to the task.

Volunteer hours granted for completion of the task: 1 hour

**Comment by yufanwang07** [comment]
I need one more day...

**Comment by akashamalNA** [comment]
Whoops didn't realize that I assigned myself.

**Comment by KL1217** [comment]
I will extend the due date to Aug 28.

**Comment by yufanwang07** [comment]
First crude result: Zip file below. There may or may not be a further revision, since I did a sort of a "check-up"
NOTE: This took a lot longer than it should have taken, since I started taking 2 other classes.

[Mschen Contact.zip](https://github.com/hicodingclub/askmschen-front/files/5144792/Mschen.Contact.zip)

**Comment by yufanwang07** [comment]
FIRST REVISION: Zip file below. This is probably the last and only revision, since everything is functioning correctly.
NOTE: I couldn't find something that might work for a bilibili icon, so I just used a TV for now. I also couldn't find a way to create a new unicode character, so, yeah...
EDIT: Fixed animation on social media buttons in mobile mode
EDIT: Deleted all unnecessary CSS.

[Mschen Contact REVISION 1.zip](https://github.com/hicodingclub/askmschen-front/files/5144794/Mschen.Contact.zip)

**Comment by yufanwang07** [comment]
LAST REVISION: Zip file below. 
NOTE: Still no bilibili button. I think the only solution is to create a unicode character.
EDIT: Fixed BiliBili icon theme color. It was slightly off.
FIXED: Minor animation issues.

[Mschen Contact LAST REVISION.zip](https://github.com/hicodingclub/askmschen-front/files/5145783/Mschen.Contact.zip)
